version: '3.4'

services:
  helloworld:
    image: helloworld
    build:
      context: .
      dockerfile: HelloWorld/Dockerfile

  secondconsoleapp:
    image: secondconsoleapp
    build:
      context: .
      dockerfile: SecondConsoleApp/Dockerfile

  helloworld.workerservice:
    image: helloworldworkerservice
    build:
      context: .
      dockerfile: HelloWorldWorkerService/Dockerfile