version: '3.4'

services:
  # helloworld:
  #   image: helloworld
  #   build:
  #     context: .
  #     dockerfile: HelloWorld/Dockerfile

  # secondconsoleapp:
  #   image: secondconsoleapp
  #   build:
  #     context: .
  #     dockerfile: SecondConsoleApp/Dockerfile

  # helloworld.workerservice:
  #   image: helloworldworkerservice
  #   build:
  #     context: .
  #     dockerfile: HelloWorldWorkerService/Dockerfile

  bandwidthtester.workerservice:
    image: bandwidthtesterworkerservice
    build: 
      context: .
      dockerfile: BandwidthTester/Dockerfile

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - ./seq-data:/data